name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: archlinux
      volumes:
        - /dev:/dev
      options:
        --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        # shell: bash
        run: ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: arch.qcow2

#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     container:
#       image: archlinux

#       - name: Run build script
#         run: ./.github/build.sh
#         

# jobs:
#   example-job:
#     name: Save output
#     steps:
#       - shell: bash
#         run: |
#           expr 1 + 1 > output.log
#       - name: Upload output file
#         uses: actions/upload-artifact@v3
#         with:
#           name: output-log-file
#           path: output.log
