name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: archlinux
#      volumes:
#        - /dev:/dev
      options:
        --privileged
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Build script
        run: ./build.sh
        # shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: arch.qcow2
          path: arch.qcow2
          retention-days: 7


#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     container:
#       image: archlinux

#       - name: Run build script
#         run: ./.github/build.sh
#         

# jobs:
#   example-job:
#     name: Save output
#     steps:
#       - shell: bash
#         run: |
#           expr 1 + 1 > output.log
#       - name: Upload output file
#         uses: actions/upload-artifact@v3
#         with:
#           name: output-log-file
#           path: output.log
