name: Test
on:
  push:
    branches: [ main ]
jobs:
  list:
    name: List dir
    runs-on: ubuntu-latest
    steps:
      - name: List dir
        run: |
          pwd
          ls -alR
          ls -alR $HOME
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     container:
#       image: archlinux
#       volumes:
#         - /dev:/dev
#       - name: Run build script
#         run: ./.github/build.sh
#         shell: bash

# jobs:
#   example-job:
#     name: Save output
#     steps:
#       - shell: bash
#         run: |
#           expr 1 + 1 > output.log
#       - name: Upload output file
#         uses: actions/upload-artifact@v3
#         with:
#           name: output-log-file
#           path: output.log
